name: Bug report
description: "Create a report to help us improve"
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      value: |-
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
  - type: textarea
    id: desktop_info
    attributes:
      label: Desktop
      description: "Please complete the following information if your problem is related to desktop devices:"
      value: |-
        - OS [e.g. Arch]:
        - Browser [e.g. Firefox]:
        - Version [e.g. 107.0.1]:
  - type: textarea
    id: smartphone_info
    attributes:
      label: Smartphone
      description: "Please complete the following information if your problem is related to mobile devices:"
      value: |-
        - Device [e.g. iPhone 14]:
        - OS [e.g. iOS 16.1.2]:
        - Browser [e.g. Safari]:
        - Version [e.g. 16.1]:
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
